# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/chjcn2csx5bwyfihrgijhfkvkpcgz243-hm-session-vars.fish

starship init fish | source

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases
    alias la 'ls -a'
    alias ll 'ls -l'
    alias nixin 'sudo nixos-rebuild switch'
    alias nixout 'sudo nix-collect-garbage -d'
    alias nixup 'sudo nixos-rebuild switch --upgrade && sudo home-manager switch'

    # Interactive shell initialisation
    if test "$TERM" != dumb
        /nix/store/2avzd018c5kcbb1h0djc04lzrp2ki607-starship-1.23.0/bin/starship init fish | source

    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/zelda/.local/share/fish/home-manager_generated_completions" $post
    end

end
